### ISSUE TITLE
Decoder not working?

### ISSUE THREAD

**Issue by tylerburnsveg** [defensivedepth/Sysmon_OSSEC#2]
Is this decoder still working with the latest version of OSSEC on github? I know there were problems with the eventchannel format that were fixed recently, but I saved this decoder into my local_decoder.xml file and tried using some of the process anomaly rules, but none of my rules seem to be picking up on any of the field mappings from the decoder (status, extra_data, etc). Was this decoder created for Sysmon v2.0 or Sysmon v1.0 (Apparently there is a version 3 coming out soon as well)? Can't seem to get this to work. Rules using just a standard <match> option will trigger, but I need to be able to map the rule to the fields in the custom decoder.

**Comment by defensivedepth** [comment]
Which version of OSSEC on GH are you referring to?

Using [Logtest](http://ossec-docs.readthedocs.org/en/latest/programs/ossec-logtest.html), can you verify that the decoder is in fact working correctly?

**Comment by tylerburnsveg** [comment]
Thanks for the response. I downloaded the latest master release on github and updated the server. I turned debugging on on the agent and found that the eventchannel logs hand line breaks in them and that is why the decoder wasn't working. Then I realized that I installed the latest version of OSSEC on the server, but not on the agent side. So I compile a new agent on the server and installed it on the client and now the log is being sent on one line like it should be. Your decoder is working great now. Nice work on this, good stuff. Thanks again.

**Comment by defensivedepth** [comment]
Fantastic. 

If you are going to run the process anomaly rules, there will defintely be some false-positives. Feel free to [comment/edit this doc](defensivedepth.com/windows-processes), which is what the ruleset is based on. I plan on tweaking the current ruleset within the next month.
